/*
 * Nscp_BDTPolicyControl Service API
 *
 * The Nscp_BDTPolicyControl Service is used by an NF service consumer to
 * retrieve background data transfer policies from the SCP and to update the SCP with
 * the background data transfer policy selected by the NF service consumer.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"os"

	"github.com/sirupsen/logrus"
	"github.com/urfave/cli"

	"github.com/free5gc/scp/logger"
	"github.com/free5gc/scp/service"
)

var SCP = &service.SCP{}

var appLog *logrus.Entry

func init() {
	appLog = logger.AppLog
}

func main() {
	app := cli.NewApp()
	app.Name = "scp"
	app.Usage = "5G Service Communication Proxy"
	app.Action = action
	app.Flags = SCP.GetCliCmd()

	if err := app.Run(os.Args); err != nil {
		appLog.Errorf("SCP Run Error: %v", err)
	}
}

func action(c *cli.Context) error {
	if err := SCP.Initialize(c); err != nil {
		logger.CfgLog.Errorf("%+v", err)
		return fmt.Errorf("Failed to initialize !!")
	}

	SCP.Start()

	return nil
}
