info:
  version: 1.0.0
  description: SCP initial local configuration

configuration:
  scpName: SCP # the name of this CHF
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: 127.0.0.113 # IP used to register to NRF
    bindingIPv4: 127.0.0.113  # IP used to bind the service
    port: 8000              # port used to bind the service
    tls: # the local path of TLS key
      pem: config/TLS/scp.pem # CHF TLS Certificate
      key: config/TLS/scp.key # CHF TLS Private key
  nrfUri: http://127.0.0.10:8000  # a valid URI of NRF

# the kind of log output
  # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  # ReportCaller: enable the caller report or not, value: true or false
logger:
  SCP:
    debugLevel: info
    ReportCaller: false
  PathUtil:
    debugLevel: info
    ReportCaller: false
  OpenApi:
    debugLevel: info
    ReportCaller: false
